README.md

Created a basic bilingual description of the service.

Drafted READ.ME description v1

---

README.md

Updated readme docs for local installation

docs: updated readme install docs

---

app/config/i18n.js
app/locales/en.json
app/locales/en.yaml
app/locales/fr.json
app/nuxt.config.js
app/package-lock.json
app/package.json
app/tsconfig.json

feat: add i18n

---

.github/workflows/tf_apply.yml

Run terraform plan after a merge

Terraform Apply

---

.github/workflows/tf_plan.yml

Add tfplan to github actions [Trello card](https://trello.com/c/oWTILCoC/117-add-a-tf-plan-to-github-pipeline)

Add tf plan for staging app

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml

Terraform apply staging app

---

.github/workflows/tf_apply.yml

add contentful cda access token to tf apply

Add contentful cda access token to tf apply

---

infrastructure/terragrunt/aws/app/api_gateway.tf
infrastructure/terragrunt/aws/app/certificate.tf

Fixes #13 
Adds a certificate in route 53 for terraform

ci: tf certificate

---

infrastructure/terragrunt/aws/app/api_gateway.tf

Certificate change (terraform)

ci: tf certificate change

---

.github/workflows/tf_apply.yml
infrastructure/terragrunt/aws/app/api_gateway.tf
infrastructure/terragrunt/aws/app/certificate.tf
infrastructure/terragrunt/aws/app/inputs.tf
infrastructure/terragrunt/aws/hosted-zone/inputs.tf
infrastructure/terragrunt/aws/hosted-zone/outputs.tf
infrastructure/terragrunt/aws/hosted-zone/route53.tf
infrastructure/terragrunt/env/staging/app/terragrunt.hcl
infrastructure/terragrunt/env/staging/env_vars.hcl
infrastructure/terragrunt/env/staging/hosted-zone/terragrunt.hcl

Terraform files to plan & apply for setting route53 subdomains and validation

Certificates and subdomains app.learning-resources.cdssandbox.xyz

---

infrastructure/terragrunt/aws/app/lambda.tf

Increase lambda timeout to 5 mins

Increase lambda timeout to 5 mins

---

Dockerfile
app/layouts/default.vue
app/layouts/expandedSearch.vue
app/pages/category/_slug.vue
app/pages/index.vue

Add error page, and also change lambda handler path in dockerfile

Error page and layout

---

infrastructure/terragrunt/aws/app/amplify.tf

fix: update build directory

---

app/.eslintrc.js

This PR fixes the lint issues found in #40

Update eslint file to handle nuxtjs

---

infrastructure/terragrunt/aws/app/amplify.tf

Pull Request previews on Amplify

Enable pull request preview on amplify

---

app/package-lock.json
app/pages/topic/_topic.vue

Removed `environments/master` from the Contentful endpoint

fix: contentful endpoint - removed environment master

---

app/components/Header.vue

Fixes language switching between the different domains

fix: change link to use external link for domains to work

---

.github/workflows/axe.yml

ci: change working folder

---

README.md
infrastructure/terragrunt/aws/app/amplify.tf

Add badges to readme
also removes test phase from amplify

docs: add badges to readme

---

app/nuxt.config.js

---
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …

feat: add differentDomains

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
app/nuxt.config.js
app/package-lock.json
app/package.json
infrastructure/terragrunt/aws/app/amplify.tf
infrastructure/terragrunt/aws/app/inputs.tf

Add google analytics

---

app/nuxt.config.js
app/package-lock.json
app/package.json
app/plugins/vue-gtag.js

Remove google analytics nuxt package and try out gtags instead for google analytics 4

Change google analytics package, use gtags

---

app/components/Banner.vue
app/locales/en.json
app/locales/fr.json
frontend/locales/en.json
frontend/locales/fr.json

feat: update content

---

app/plugins/vue-gtag.js

chore: change function

---

app/plugins/vue-gtag.js

Check if ID in the config file gets populated correctly

Google Analytics ID - check if populating

---

app/locales/en.json
app/locales/fr.json
app/pages/index.vue
frontend/locales/en.json
frontend/locales/fr.json

---
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …

feat: index page add subtitle

---

app/locales/en.json
app/locales/fr.json
app/pages/index.vue
frontend/locales/en.json
frontend/locales/fr.json

---
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …

feat: landing page and translation

---

app/locales/en.json
app/locales/fr.json
app/pages/index.vue
frontend/locales/en.json
frontend/locales/fr.json

---
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …

feat: landing copy

---

app/nuxt.config.js

Remove workbox completely

---

app/components/Footer.vue
app/components/Header.vue
app/nuxt.config.js

Opening this PR to attempt to fix all hydration issues for bilingual switching

Hydration issues

---

infrastructure/terragrunt/aws/app/amplify_staging.tf
infrastructure/terragrunt/env/staging/app/terragrunt.hcl

* ci: add staging environement on amplify, modify minor prod settings (names)
* ci: update amplify values
* ci: fix for invalid value for stage
* ci: linting
---
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de …

Add staging environment (#158)

---

app/components/Header.vue

- Added lang attribute to language toggle

feat: add lang attribute to lang toggle

---

app/locales/fr.json

Fixes #173
Related resources translation

Minor change to translation string

---

app/components/Footer.vue

Fixes #174 
Remove footer link to Visit Canada.ca / Visitez Canada.ca

Remove Canada.ca link in footer

---

app/components/Breadcrumbs.vue

- fix squished items in mobile view 
- created nav section "breadcrumbs"
- delineated  current page

fix: breadcrumbs accessibility

---

app/components/Header.vue
app/layouts/expandedSearch.vue
app/locales/en.json
app/locales/fr.json
app/pages/resource/_resource.vue
app/tailwind.config.js

> #224 
Feature F3:
- New feature "Jump to" links (aka anchor links) for resources
- Ability to jump to headings within a resource page
- Ability to share url link that goes to specific section of resource page
- Ability for user to visualize approximate page position within resource page
---

feat: resource jump links

---

app/components/PageSectionHeading.vue
app/components/PageTitle.vue
app/components/SectionDivider.vue
app/components/list-items/CollectionListItem.vue
app/locales/en.json
app/locales/fr.json
app/nuxt.config.js
app/package-lock.json
app/package.json
app/pages/collection/_collection.vue
app/pages/topic/_topic.vue
app/utils/generateRoutes.js
app/utils/listItemsUtility.js
app/utils/pathUtility.js
app/utils/queries.js

> #236 
> #236 (F1)
> First crack at resource grouping (aka collections)

feat: resource collections

---

app/locales/en.json
app/locales/fr.json

Since we use "related collections", reverting "browse by content" to "browse collections"

Collections copy edit

---

app/locales/en.json
app/locales/fr.json

Changes made for brevity and parallel consistency for now.

Content tweaking

---

app/components/Header.vue
app/layouts/expandedSearch.vue
app/nuxt.config.js
app/package-lock.json
app/package.json
app/pages/index.vue
app/pages/legal/_legal.vue
app/pages/resource/_resource.vue
app/pages/topic/_topic.vue
app/store/index.js
app/utils/queries.js

> #241 
> Drop down topic menu
> Top sticky nav bar

feat: topic menu

---

app/layouts/blank.vue
app/pages/testlanding.vue

> #255
Adds a new link to a page that doesn't have anything on it, that we can share with our testers beforehand to verify that they are able to access our website.
**To test:** https://pr-256.d3eik05156ec7t.amplifyapp.com/testlanding/
<kbd>
</kbd>

feat: add blank landing page for ux testing

---

app/plugins/vue-gtag.js

Hotfix for testing out how google analytics works with our config

fix: add gtag option for tracking screenviews

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
app/README.md
app/nuxt.config.js
app/package-lock.json
app/package.json
infrastructure/terragrunt/aws/app/amplify.tf
infrastructure/terragrunt/aws/app/amplify_staging.tf
infrastructure/terragrunt/aws/app/inputs.tf
scripts/set_envs.sh

Add sentry

---

app/locales/fr.json

Minor improvement to use more familiar language in French.

Minor copyedit - change "Thèmes" to "Sujets" in FR

---

infrastructure/terragrunt/aws/app/amplify.tf
infrastructure/terragrunt/aws/app/amplify_staging.tf

fix: hotfix for failing build

---

app/pages/resource/_resource.vue
app/utils/contentTypes.js
app/utils/queries.js

> #337 
> fixes issue where entry hyperlinks were displayed incorrect within a resource

fix: link displays entry-hyperlink id

---

app/components/Header.vue
app/pages/resource/_resource.vue
app/utils/contentTypes.js
app/utils/queries.js

> #269 
> Will tab through open menu before focusing on the language switcher

fix: open menu tab order

---

app/pages/resource/_resource.vue
app/pages/topic/_topic.vue
app/tailwind.config.js
app/utils/generateRoutes.js
app/utils/richTextRenderOptions.js

> #361 
> Addresses the technical debt of: duplication of rich text rendering code 
> by consolidating the rich text rendering code of resource pages and other pages

refactor: consolidate rich text rendering options

---

app/components/headings/Heading1.vue
app/pages/about.vue
app/pages/collection/_collection.vue
app/pages/contact.vue
app/pages/legal/_legal.vue
app/pages/resource/_resource.vue
app/pages/topic/_topic.vue

> #180 
> Fixes inconsistent application of H1s across the various site pages

fix: H1 consistency across site

---

app/pages/resource/_resource.vue
app/pages/topic/_topic.vue
app/utils/listItemsUtility.js

> #313 
> Fixes: linking a draft resource to topic or resource will break that topic or resource

fix: linked draft resource breaks topic or resource

---

app/components/Banner.vue
app/components/Header.vue
app/layouts/expandedSearch.vue
app/pages/index.vue
app/pages/resource/_resource.vue

> Resolves #370 - Unstick alpha banner
> Fixes #350 - Breadcrumb 'home' link cut off on mobile

feat: unstick alpha banner

---

app/.eslintrc.js
app/components/feature-flags/Feature.vue
app/featureNames.js
app/nuxt.config.js
app/utils/constants.js
app/utils/featureConfigUtil.ts

> #300 
> Adds capability to set feature flags either directly in Nuxt config or via environment variables using:
> booleans, integers, or JSON

feat: feature flags

---

app/nuxt.config.js
app/pages/index.vue
app/utils/constants.js

feat: alternate landing headline and feature flag demo

---

app/components/Header.vue
app/locales/en.json
app/locales/fr.json
app/nuxt.config.js
app/pages/about.vue
app/pages/contact.vue
app/pages/index.vue
app/pages/resource/_resource.vue
app/pages/topic/_topic.vue
app/utils/generateRoutes.js
app/utils/pathUtility.js
app/utils/paths.js

refactor: remove duplication of i18n path names

---

app/components/SkipToContentLink.vue
app/layouts/expandedSearch.vue
app/locales/en.json
app/locales/fr.json

> #409 
> Adds "Passer au contenu principal" as french translation for skip to content link

fix: add french to skip to content link

---

app/components/Header.vue
app/locales/en.json
app/locales/fr.json

> #408 
> Remove Learning Resources abbreviation ('LR')

fix: remove "LR/RA" acronym in header

---

app/locales/en.json

One line/word change for consistency

Match EN / FR " for skip to main content

---

app/components/PageContents.vue
app/components/list-items/ExternalResourceListItem.vue
app/locales/en.json
app/locales/fr.json
app/pages/resource/_resource.vue
app/utils/constants.js
app/utils/listItemsUtility.js
app/utils/queries.js

- #296 
> Adding new external resource component

feat: add external resource component
